"""initial schema

Revision ID: f782f2b25b23
Revises: 
Create Date: 2026-02-10 12:52:49.745507
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f782f2b25b23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent: skip tables that already exist (pre-alembic databases)
    from sqlalchemy import inspect as sa_inspect
    conn = op.get_bind()
    existing = set(sa_inspect(conn).get_table_names())

    if 'assets' in existing:
        return  # All initial tables exist — stamped by prior non-alembic setup

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('os_hint', sa.String(), nullable=True),
    sa.Column('bigr_category', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('scan_method', sa.String(), nullable=False),
    sa.Column('first_seen', sa.String(), nullable=False),
    sa.Column('last_seen', sa.String(), nullable=False),
    sa.Column('manual_category', sa.String(), nullable=True),
    sa.Column('manual_note', sa.String(), nullable=True),
    sa.Column('is_ignored', sa.Integer(), nullable=False),
    sa.Column('switch_host', sa.String(), nullable=True),
    sa.Column('switch_port', sa.String(), nullable=True),
    sa.Column('switch_port_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'mac', name='uq_asset_ip_mac')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('cn', sa.String(), nullable=True),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('issuer_org', sa.String(), nullable=True),
    sa.Column('valid_from', sa.String(), nullable=True),
    sa.Column('valid_to', sa.String(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.Column('key_algorithm', sa.String(), nullable=True),
    sa.Column('is_self_signed', sa.Integer(), nullable=False),
    sa.Column('is_expired', sa.Integer(), nullable=False),
    sa.Column('days_until_expiry', sa.Integer(), nullable=True),
    sa.Column('san', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'port', name='uq_cert_ip_port')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('scan_method', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('total_assets', sa.Integer(), nullable=False),
    sa.Column('is_root', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subnets',
    sa.Column('cidr', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('last_scanned', sa.String(), nullable=True),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cidr')
    )
    op.create_table('switches',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('community', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('last_polled', sa.String(), nullable=True),
    sa.Column('mac_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('host')
    )
    op.create_table('asset_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('detected_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_assets',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('open_ports', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('bigr_category', sa.String(), nullable=False),
    sa.Column('raw_evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('scan_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_assets')
    op.drop_table('asset_changes')
    op.drop_table('switches')
    op.drop_table('subnets')
    op.drop_table('scans')
    op.drop_table('certificates')
    op.drop_table('assets')
    # ### end Alembic commands ###
