"""Alert data models for BİGR Discovery."""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime, timezone


class AlertSeverity(str, enum.Enum):
    """Alert severity levels with numeric ordering."""

    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"

    @property
    def level(self) -> int:
        """Numeric level for ordering: CRITICAL(3) > WARNING(2) > INFO(1)."""
        return _SEVERITY_LEVELS[self]


_SEVERITY_LEVELS: dict[AlertSeverity, int] = {
    AlertSeverity.CRITICAL: 3,
    AlertSeverity.WARNING: 2,
    AlertSeverity.INFO: 1,
}


class AlertType(str, enum.Enum):
    """Types of alerts the engine can produce."""

    NEW_DEVICE = "new_device"
    ROGUE_DEVICE = "rogue_device"
    PORT_CHANGE = "port_change"
    CATEGORY_CHANGE = "category_change"
    DEVICE_MISSING = "device_missing"
    MASS_CHANGE = "mass_change"


@dataclass
class Alert:
    """A single alert generated by the alert engine."""

    alert_type: AlertType
    severity: AlertSeverity
    ip: str
    mac: str | None
    message: str
    details: dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        """Serialize to a plain dict for channel transport."""
        return {
            "alert_type": self.alert_type.value,
            "severity": self.severity.value,
            "ip": self.ip,
            "mac": self.mac,
            "message": self.message,
            "details": self.details,
            "timestamp": self.timestamp.isoformat(),
        }

    @property
    def formatted_message(self) -> str:
        """Human-readable formatted message string."""
        return f"[{self.severity.value.upper()}] {self.alert_type.value} | {self.ip} | {self.message}"
